const FETCH_ALL = 'FETCH_ALL',
CREATE = 'CREATE',
UPDATE = 'UPDATE',
DELETE = 'DELETE',
LIKE = 'LIKE';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export {FETCH_ALL, CREATE, UPDATE, DELETE, LIKE}